import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/db_models.dart';

/// Generates a printable/shareable PDF report for a single recruit —
/// the kind of document a company might hand to an auditor, attach to a
/// hiring file, or keep as an offline record of why someone was flagged.
///
/// Deliberately conservative in design (navy/gold matching the in-app
/// theme, but no decorative flourishes) since this is a document people
/// may print, forward by email, or present as evidence in a dispute.
class RecruitPdfService {
  static final _dateFmt = DateFormat('d MMMM yyyy');
  static final _dateShortFmt = DateFormat('d MMM yyyy');

  static const _navy = PdfColor.fromInt(0xFF0A1628);
  static const _gold = PdfColor.fromInt(0xFFD4A017);
  static const _steel = PdfColor.fromInt(0xFF1E3A5F);
  static const _textMuted = PdfColor.fromInt(0xFF55606E);
  static const _danger = PdfColor.fromInt(0xFFB8202C);
  static const _success = PdfColor.fromInt(0xFF1A8F82);
  static const _warning = PdfColor.fromInt(0xFFB07F0E);
  static const _lightGrey = PdfColor.fromInt(0xFFF2F3F5);

  static PdfColor _statusColor(String status) {
    switch (status) {
      case 'clear':
        return _success;
      case 'flagged':
        return _warning;
      case 'terminated':
      case 'suspended':
        return _danger;
      default:
        return _textMuted;
    }
  }

  static PdfColor _conductColor(String type) {
    switch (type) {
      case 'commendation':
        return _success;
      case 'warning':
        return _warning;
      case 'suspension':
        return const PdfColor.fromInt(0xFFC2410C);
      case 'termination':
      case 'misconduct':
        return _danger;
      default:
        return _textMuted;
    }
  }

  static String _conductLabel(String type) {
    switch (type) {
      case 'commendation':
        return 'Commendation';
      case 'warning':
        return 'Warning';
      case 'suspension':
        return 'Suspension';
      case 'termination':
        return 'Termination';
      case 'misconduct':
        return 'Misconduct';
      default:
        return type;
    }
  }

  /// Builds the PDF document in memory and returns the raw bytes, ready to
  /// be saved, shared, or sent straight to a printer via the `printing`
  /// package's share/print sheets.
  static Future<List<int>> generateRecruitReport({
    required DbRecruit recruit,
    required String generatedByCompanyName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(36, 40, 36, 36),
        header: (context) => _buildPageHeader(context),
        footer: (context) => _buildPageFooter(context),
        build: (context) => [
          _buildTitleBlock(recruit),
          pw.SizedBox(height: 18),
          _buildIdentificationSection(recruit),
          pw.SizedBox(height: 18),
          if (recruit.status != 'clear') ...[
            _buildStatusWarning(recruit),
            pw.SizedBox(height: 18),
          ],
          _buildEmploymentSection(recruit),
          pw.SizedBox(height: 18),
          _buildConductSection(recruit),
          pw.SizedBox(height: 24),
          _buildSignatureBlock(generatedByCompanyName),
        ],
      ),
    );

    return doc.save();
  }

  // ── Sections ─────────────────────────────────────────────────────────

  static pw.Widget _buildPageHeader(pw.Context context) {
    if (context.pageNumber == 1) return pw.SizedBox();
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Text(
        'THE SECURITY ZONE — Recruit Verification Report',
        style: pw.TextStyle(fontSize: 8, color: _textMuted),
      ),
    );
  }

  static pw.Widget _buildPageFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.center,
      margin: const pw.EdgeInsets.only(top: 12),
      child: pw.Text(
        'Page ${context.pageNumber} of ${context.pagesCount}  ·  '
        'Generated by The Security Zone  ·  '
        'Confidential — for authorized personnel only',
        style: pw.TextStyle(fontSize: 7.5, color: _textMuted),
      ),
    );
  }

  static pw.Widget _buildTitleBlock(DbRecruit recruit) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(18),
      decoration: pw.BoxDecoration(
        color: _navy,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Container(
            width: 36,
            height: 36,
            decoration: pw.BoxDecoration(
              shape: pw.BoxShape.circle,
              border: pw.Border.all(color: _gold, width: 1.5),
            ),
            alignment: pw.Alignment.center,
            child: pw.Text(
              'SZ',
              style: pw.TextStyle(
                color: _gold,
                fontWeight: pw.FontWeight.bold,
                fontSize: 12,
              ),
            ),
          ),
          pw.SizedBox(width: 14),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'THE SECURITY ZONE',
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    letterSpacing: 1.2,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  'Recruit Verification Report',
                  style: pw.TextStyle(color: _gold, fontSize: 10),
                ),
              ],
            ),
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                'Generated',
                style: pw.TextStyle(color: PdfColors.grey400, fontSize: 7.5),
              ),
              pw.Text(
                _dateFmt.format(DateTime.now()),
                style: pw.TextStyle(color: PdfColors.white, fontSize: 9),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildIdentificationSection(DbRecruit recruit) {
    final statusColor = _statusColor(recruit.status);
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            flex: 3,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  recruit.fullName,
                  style: pw.TextStyle(
                      fontSize: 16, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 8),
                _kv('ID Number', recruit.idNumber),
                _kv('Phone', recruit.phone ?? 'Not provided'),
                _kv('Region', recruit.region),
                _kv('Registered',
                    _dateShortFmt.format(recruit.registeredAt)),
                _kv(
                  'Fingerprint on File',
                  recruit.fingerprintHash != null ? 'Yes' : 'No',
                ),
              ],
            ),
          ),
          pw.Expanded(
            flex: 1,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Container(
                  padding:
                      const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                  decoration: pw.BoxDecoration(
                    color: PdfColor(
                        statusColor.red, statusColor.green, statusColor.blue,
                        0.12),
                    border: pw.Border.all(color: statusColor, width: 1),
                    borderRadius: pw.BorderRadius.circular(20),
                  ),
                  child: pw.Text(
                    recruit.statusLabel,
                    style: pw.TextStyle(
                      color: statusColor,
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                      letterSpacing: 1,
                    ),
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  '${recruit.employmentHistory.length} '
                  '${recruit.employmentHistory.length == 1 ? 'company' : 'companies'}',
                  style: pw.TextStyle(fontSize: 9, color: _textMuted),
                ),
                pw.Text(
                  '${recruit.conductRecords.length} '
                  '${recruit.conductRecords.length == 1 ? 'record' : 'records'}',
                  style: pw.TextStyle(fontSize: 9, color: _textMuted),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildStatusWarning(DbRecruit recruit) {
    final color = _statusColor(recruit.status);
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColor(color.red, color.green, color.blue, 0.08),
        border: pw.Border.all(color: color, width: 1),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        children: [
          pw.Container(
            width: 4,
            height: 24,
            color: color,
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Text(
              'This recruit has a ${recruit.statusLabel.toLowerCase()} flag on file. '
              'Review the conduct records below before making an employment decision.',
              style: pw.TextStyle(color: color, fontSize: 9.5),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildEmploymentSection(DbRecruit recruit) {
    final sorted = [...recruit.employmentHistory]
      ..sort((a, b) => b.startDate.compareTo(a.startDate));

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionHeader('EMPLOYMENT HISTORY'),
        pw.SizedBox(height: 8),
        if (sorted.isEmpty)
          pw.Text('No employment history on file.',
              style: pw.TextStyle(fontSize: 9.5, color: _textMuted))
        else
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            columnWidths: const {
              0: pw.FlexColumnWidth(2.5),
              1: pw.FlexColumnWidth(1.8),
              2: pw.FlexColumnWidth(1.6),
              3: pw.FlexColumnWidth(2.3),
            },
            children: [
              pw.TableRow(
                decoration: pw.BoxDecoration(color: _lightGrey),
                children: [
                  _tableHeaderCell('Company'),
                  _tableHeaderCell('Role'),
                  _tableHeaderCell('Period'),
                  _tableHeaderCell('Exit Reason'),
                ],
              ),
              ...sorted.map((e) {
                final period = e.isCurrent
                    ? '${_dateShortFmt.format(e.startDate)} — Present'
                    : '${_dateShortFmt.format(e.startDate)} — '
                        '${_dateShortFmt.format(e.endDate!)}';
                return pw.TableRow(
                  children: [
                    _tableCell(e.companyName, bold: true),
                    _tableCell(e.role),
                    _tableCell(period),
                    _tableCell(
                      e.exitReason ?? (e.isCurrent ? 'Current employer' : '—'),
                      color: e.exitReason != null ? _danger : null,
                    ),
                  ],
                );
              }),
            ],
          ),
      ],
    );
  }

  static pw.Widget _buildConductSection(DbRecruit recruit) {
    final sorted = [...recruit.conductRecords]
      ..sort((a, b) => b.incidentDate.compareTo(a.incidentDate));

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionHeader('CONDUCT RECORDS (${sorted.length})'),
        pw.SizedBox(height: 8),
        if (sorted.isEmpty)
          pw.Text('No conduct records on file.',
              style: pw.TextStyle(fontSize: 9.5, color: _textMuted))
        else
          pw.Column(
            children: sorted.map((c) {
              final color = _conductColor(c.type);
              return pw.Container(
                margin: const pw.EdgeInsets.only(bottom: 8),
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColor(color.red, color.green, color.blue, 0.06),
                  border: pw.Border.all(color: color, width: 0.75),
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Container(
                          padding: const pw.EdgeInsets.symmetric(
                              horizontal: 7, vertical: 2),
                          decoration: pw.BoxDecoration(
                            color: PdfColor(
                                color.red, color.green, color.blue, 0.18),
                            borderRadius: pw.BorderRadius.circular(10),
                          ),
                          child: pw.Text(
                            _conductLabel(c.type).toUpperCase(),
                            style: pw.TextStyle(
                              color: color,
                              fontSize: 7.5,
                              fontWeight: pw.FontWeight.bold,
                              letterSpacing: 0.6,
                            ),
                          ),
                        ),
                        pw.Text(
                          _dateShortFmt.format(c.incidentDate),
                          style: pw.TextStyle(fontSize: 8, color: _textMuted),
                        ),
                      ],
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      c.companyName,
                      style: pw.TextStyle(
                          fontSize: 9,
                          fontWeight: pw.FontWeight.bold,
                          color: _steel),
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(c.description,
                        style: const pw.TextStyle(fontSize: 9.5)),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      'Reported by: ${c.reportedBy}',
                      style: pw.TextStyle(
                          fontSize: 8,
                          color: _textMuted,
                          fontStyle: pw.FontStyle.italic),
                    ),
                  ],
                ),
              );
            }).toList(),
          ),
      ],
    );
  }

  static pw.Widget _buildSignatureBlock(String companyName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 10),
        pw.Text(
          'This report was generated by $companyName via The Security Zone '
          'platform and reflects records on file at the time of generation. '
          'Records are contributed by participating private security companies '
          'and are subject to dispute and correction through the platform.',
          style: pw.TextStyle(fontSize: 8, color: _textMuted),
        ),
      ],
    );
  }

  // ── Small helpers ────────────────────────────────────────────────────

  static pw.Widget _sectionHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 4),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _gold, width: 1.5)),
      ),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: _navy,
          letterSpacing: 1,
        ),
      ),
    );
  }

  static pw.Widget _kv(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 110,
            child: pw.Text(label,
                style: pw.TextStyle(fontSize: 9, color: _textMuted)),
          ),
          pw.Text(value,
              style:
                  pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _tableHeaderCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
      child: pw.Text(
        text,
        style: pw.TextStyle(
            fontSize: 8, fontWeight: pw.FontWeight.bold, color: _navy),
      ),
    );
  }

  static pw.Widget _tableCell(String text,
      {bool bold = false, PdfColor? color}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 8.5,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: color,
        ),
      ),
    );
  }
}
